### ISSUE TITLE
How do I tell which version I have 1.0 or 1.2

### ISSUE THREAD

**Issue by ndw8** [airvolute/dcs-deploy#11]
Can you please tell me how to identify if I have a v1.0 or v1.2 board?

**Comment by MartinSedlacek** [comment]
You can refer to the bottom of the board of DCS.Pilot, there should be label referring to the revision.

Another way is to check the Control header at the top of the board:
For v1.0 board it should be 4 pin header.
[DCS 1.0 Docs](https://docs.airvolute.com/airvolute-dronecore.suite/dcs1/dronecore.pilot_header/dcs1.pilot-v1.0/dronecore.pilot-connector-description-and-pins-assignment#control)

For v1.2 board it should be 6 pin header.
 [DCS 1.2 Docs](https://docs.airvolute.com/airvolute-dronecore.suite/dcs1/dronecore.pilot_header/dcs1.pilot-v1.2/dronecore.pilot-connector-description-and-pins-assignment#control)

**Comment by ndw8** [comment]
Thanks
