### ISSUE TITLE
Jet pack 5.1 on v1.0

### ISSUE THREAD

**Issue by ndw8** [airvolute/dcs-deploy#12]
Hi, are you able to provide support in how to flash jetpack 5.1 to a v1.0 board?

**Comment by jRodina** [comment]
@ndw8 jetpack 5.1 needs a lot of disk space. V1.0 board doesn't have M.2 interface for SSD, which makes it hard to use with Orin NX (it doesn't have internal eMMC); with Xavier NX it has an issue with eMMC space, so that is why we do not have direct support for jetpack 5.1

**Comment by ndw8** [comment]
After flashing we move the rootfs onto the SD card and then boot from there. It is slower but gives sufficient storage. We would prefer to keep developing with the v1.0 board if possible.

Do you think you would be able to assist in setting up jetpack 5.1?
