### ISSUE TITLE
DroneCore2.0 - avt configuration

### ISSUE THREAD

**Issue by ovad97** [airvolute/dcs-deploy#16]
Hi, what is the difference between the "512" and the "512_avt" l4t versions?
The configs that I'm looking into are `config_7` and `config_8` in the jp_512_20_configs branch.
Thanks in advance

**Comment by MartinSedlacek** [comment]
Hi, `512_avt` is config targeted at Allied Vision cameras (it contains some additional modifications related to the given cameras).

If you are interested in standard JP 5.1.2 for DroneCore use `512`.
