### ISSUE TITLE
ethernet interface

### ISSUE THREAD

**Issue by B4njoS** [airvolute/dcs-deploy#2]
Hey!
I'm trying to install the dcs_deploy the way you wrote.
I'm getting stuck when the boot is finished.. i can't run the script "after first boot" smooth and also cannot get any IP address (the lights are off when the jetson in on after boot, when I typing the commands " $ sudo ip link set down eth0 " " $sudo ip lonk set up eth0 " I can see the eth0 interface when typing " $ ifconfig " but I cannot get any IP addresses, also the light turn on after those commands.

**Comment by eMrazSVK** [comment]
Hello, 

Could you please possibly re-flash the device and show the output after the very first boot after flashing? Please run this command and post the output here, thanks. 
```
journalctl -u dcs_first_boot
```
---
It's not clear to me, what exactly you mean by saying:
>  i can't run the script "after first boot" smooth
Are you trying to run the `dcs_first_boot.sh` manually? 

To the ethernet issue - could you please describe more precisely what devices are connected to the DCS or what are you trying to achieve? Thank you, I'll be happy to assist.

**Comment by B4njoS** [comment]
![Screenshot from 2023-07-24 03-43-46](https://github.com/airvolute/dcs-deploy/assets/117942386/49addbea-4132-4941-b6b2-7d3fff82717e)
![WhatsApp Image 2023-07-24 at 10 54 09](https://github.com/airvolute/dcs-deploy/assets/117942386/8fe79c77-29d0-4fc8-a3a8-23e4c03895df)

![Screenshot from 2023-07-24 03-50-11](https://github.com/airvolute/dcs-deploy/assets/117942386/2a460342-3d32-4e3d-a27d-82774467286b)
![Screenshot from 2023-07-24 03-50-29](https://github.com/airvolute/dcs-deploy/assets/117942386/fa68005b-ed0b-4570-97f5-f6a478a0da07)
![Screenshot from 2023-07-24 03-51-22](https://github.com/airvolute/dcs-deploy/assets/117942386/f1a876f7-0721-40f2-a1a9-98bce141eb96)

**Comment by B4njoS** [comment]
![Screenshot from 2023-07-24 03-56-33](https://github.com/airvolute/dcs-deploy/assets/117942386/ee47fc9e-d7d4-4cbb-9142-4968f6f39727)

**Comment by eMrazSVK** [comment]
Just try this command after boot and let me know, if it helps:
```
sudo ifconfig eth0 up
```
I tried this on freshly flashed Xavier and the Ethernet "LED's" were flashing just right, interface stayed up .

**Comment by B4njoS** [comment]
I did it but when I’m doing this command I don’t get any IP address (not a DHCP problem for sure)

**Comment by B4njoS** [comment]
I’ll try again and update you guys

**Comment by B4njoS** [comment]
it didn't worked, please let me check the DHCP again and I will update you guys soon, don't close the issue yet, tomorrow I'm going to make a fully check on the DHCP server, also I can't set a static IP address on the Jetson, you know why?

**Comment by eMrazSVK** [comment]
Hello, this might be an issue with root filesystem. You can try to checkout [3-add-maximized-rootfs-option-for-flashing](https://github.com/airvolute/dcs-deploy/tree/3-add-maximized-rootfs-option-for-flashing) branch and flash with:

```
python3 dcs_deploy.py flash xavier_nx 51 1.2 <emmc/nvme> full
```

See the last option `full`. This indicates root filesystem version. Now we have 2 options - `minimal` or `full`. What you have is minimal, so try with full. It might help.

**Comment by B4njoS** [comment]
Hello, I will try now and update you
Thanks!

**Comment by B4njoS** [comment]
Hello!
![Screenshot from 2023-07-26 04-54-49](https://github.com/airvolute/dcs-deploy/assets/117942386/3b25d5ec-ccf4-43e6-bcd5-30f8d0cf0c77)

I have flahsed the nvidia jetson but when I'm trying to ssh to 192.168.55.1 for the first time I'm getting an error on my fingerprint.
I have tried from root user and from local user, both doesn't work.

**Comment by eMrazSVK** [comment]
Just do what the output tells you to do after line `remove with`:
```
ssh-keygen ...
```

Just copy that line, run the command on your host computer and SSH into the device. This is a pretty standard, safe procedure to do.

**Comment by B4njoS** [comment]
Thank you for your help, much appreciate. Almost succeeded, just some installations like CUDA and docker.
