### ISSUE TITLE
Confusion on what version to use when building script

### ISSUE THREAD

**Issue by roby2014** [airvolute/dcs-deploy#21]
Hello again. I have the following devices+boards (check images) (both with orin_nx, using `jp_512_20_configs` branch)

<img src="https://github.com/airvolute/dcs-deploy/assets/47612455/8492d840-f53b-4714-9453-07693e57f32d" width="200">

<img src="https://github.com/airvolute/dcs-deploy/assets/47612455/cf823f8c-a91b-470a-9ed2-943ee49448a5" width="200">

Im looking at `local/config_db.json`. I'm a bit confused on what configs I should use.

From my understanding, I have a `DCS1.Pilot v1.2` (so `python3 dcs_deploy.py flash orin_nx 512 1.2 nvme full` I suppose) and `DroneCore 2 (DCS2.Pilot v1.0)` (so `python3 dcs_deploy.py flash orin_nx 512 1.0 nvme full`)

Am I right? I am a bit confused since there is version `1.0` for both DCS1 and DCS2...
Re-suggesting that you should add documentation regarding these options. (or also, add images to your dcs2.pilot-v-1.0 page: https://docs.airvolute.com/autopilots/dcs2/.pilot-boards/dcs2.pilot-v-1.0)

**Comment by eMrazSVK** [comment]
Hello, for Orin NX on Pilot board 2.0 (the smaller one), use following command:
```
python3 dcs_deploy.py flash orin_nx 512 2.0 nvme full
```
