### ISSUE TITLE
Access Jetson Orin NX 16GB UART on DCS2 

### ISSUE THREAD

**Issue by rcptk** [airvolute/dcs-deploy#24]
Hello. I need access to UART to debug what going on in the Orin NX.

As described in the docs:

![image](https://github.com/airvolute/dcs-deploy/assets/166127388/2d6a2b61-2c1c-4822-9038-7029ab4d8fcf)

![image](https://github.com/airvolute/dcs-deploy/assets/166127388/dde49a46-015b-4f36-b405-ba6e054c7ae5)

I'm using the `GPS_JET` from the `DCS2.Adapter_default v1.0` wired up to my [RS232 FTDI](https://www.sparkfun.com/products/9873) and trying to access via `sudo picocom -b 115200 /dev/ttyUSB0` (TX->RX, RX->TX, GND->GND)

I've also seen in some forums to use `/dev/ttyTHS...` but I dont have any device for that
However, I don't see any output in my terminal.

Hardware:
- orin nx 16gb
- dronecore 2
- rs232 ftdi
- usb connected to board
- 12v power supply

**Comment by vrsanskytom** [comment]
Hi, you are probably searching for Jetson debug serial port. It is located directly on the .Pilot board. Unfortunately, it's possible to access it only by soldering debug cables to the solder pads. See attached image: 
![IMG_4950](https://github.com/airvolute/dcs-deploy/assets/54900700/bd05c6c1-0946-4954-b7dc-683cf4657336)

**Comment by rcptk** [comment]
Hello. That seems to be working. Im doubtin then, what is `GPS_JET` THEN?

**Comment by vrsanskytom** [comment]
It's different Serial port from Jetson. It can be used for custom purposes.

**Comment by rcptk** [comment]
I'd still like to understand what you mean with "custom purposes", but thanks, using the pads from the image, I'm able to access the UART.
